/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package subastacliente;

/**
 *
 * @author juanc
 */
public class interfazCliente extends javax.swing.JFrame {

    /**
     * Creates new form interfazCliente
     */
    public interfazCliente() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPrincipal = new javax.swing.JPanel();
        jPanelPujas = new javax.swing.JPanel();
        jButtonPujar = new javax.swing.JButton();
        jButtonRetirarse = new javax.swing.JButton();
        jButtonAceptarProducto = new javax.swing.JButton();
        jButtonRechazarProducto = new javax.swing.JButton();
        jPanelReloj = new javax.swing.JPanel();
        jTextFieldReloj = new javax.swing.JTextField();
        jLabelTextoReloj = new javax.swing.JLabel();
        jPanelElegirProducto = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanelInfoProducto = new javax.swing.JPanel();
        jTextFieldEntrada = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaCategorias = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelPrincipal.setBackground(new java.awt.Color(235, 245, 251));
        jPanelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelPujas.setBackground(new java.awt.Color(91, 198, 240));

        jButtonPujar.setBackground(new java.awt.Color(39, 174, 96));
        jButtonPujar.setText("Pujar");

        jButtonRetirarse.setBackground(new java.awt.Color(239, 53, 53));
        jButtonRetirarse.setText("Retirarse");

        jButtonAceptarProducto.setBackground(new java.awt.Color(32, 236, 16));
        jButtonAceptarProducto.setText("Aceptar Producto");

        jButtonRechazarProducto.setBackground(new java.awt.Color(255, 35, 35));
        jButtonRechazarProducto.setText("Rechazar Producto");

        javax.swing.GroupLayout jPanelPujasLayout = new javax.swing.GroupLayout(jPanelPujas);
        jPanelPujas.setLayout(jPanelPujasLayout);
        jPanelPujasLayout.setHorizontalGroup(
            jPanelPujasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPujasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPujasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonRechazarProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonAceptarProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonPujar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonRetirarse, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelPujasLayout.setVerticalGroup(
            jPanelPujasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPujasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonPujar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonRetirarse)
                .addGap(100, 100, 100)
                .addComponent(jButtonAceptarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonRechazarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(266, Short.MAX_VALUE))
        );

        jPanelPrincipal.add(jPanelPujas, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 130, 260, 570));

        jPanelReloj.setBackground(new java.awt.Color(33, 97, 140));

        jTextFieldReloj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldRelojActionPerformed(evt);
            }
        });

        jLabelTextoReloj.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabelTextoReloj.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTextoReloj.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTextoReloj.setText("La subasta cierra en:");

        javax.swing.GroupLayout jPanelRelojLayout = new javax.swing.GroupLayout(jPanelReloj);
        jPanelReloj.setLayout(jPanelRelojLayout);
        jPanelRelojLayout.setHorizontalGroup(
            jPanelRelojLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelTextoReloj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRelojLayout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(jTextFieldReloj, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
        jPanelRelojLayout.setVerticalGroup(
            jPanelRelojLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRelojLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTextoReloj)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldReloj, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanelPrincipal.add(jPanelReloj, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 0, 260, 130));

        jPanelElegirProducto.setBackground(new java.awt.Color(52, 152, 219));
        jPanelElegirProducto.setLayout(new java.awt.GridLayout(2, 3, 5, 5));

        jPanel1.setBackground(new java.awt.Color(214, 234, 248));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 243, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 192, Short.MAX_VALUE)
        );

        jPanelElegirProducto.add(jPanel1);

        jPanel5.setBackground(new java.awt.Color(214, 234, 248));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 243, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 192, Short.MAX_VALUE)
        );

        jPanelElegirProducto.add(jPanel5);

        jPanel2.setBackground(new java.awt.Color(214, 234, 248));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 243, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 192, Short.MAX_VALUE)
        );

        jPanelElegirProducto.add(jPanel2);

        jPanel3.setBackground(new java.awt.Color(214, 234, 248));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 243, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 192, Short.MAX_VALUE)
        );

        jPanelElegirProducto.add(jPanel3);

        jPanel4.setBackground(new java.awt.Color(214, 234, 248));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 243, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 192, Short.MAX_VALUE)
        );

        jPanelElegirProducto.add(jPanel4);

        jPanel6.setBackground(new java.awt.Color(214, 234, 248));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 243, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 192, Short.MAX_VALUE)
        );

        jPanelElegirProducto.add(jPanel6);

        jPanelPrincipal.add(jPanelElegirProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 390));

        jPanelInfoProducto.setBackground(new java.awt.Color(52, 152, 219));

        javax.swing.GroupLayout jPanelInfoProductoLayout = new javax.swing.GroupLayout(jPanelInfoProducto);
        jPanelInfoProducto.setLayout(jPanelInfoProductoLayout);
        jPanelInfoProductoLayout.setHorizontalGroup(
            jPanelInfoProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 740, Short.MAX_VALUE)
        );
        jPanelInfoProductoLayout.setVerticalGroup(
            jPanelInfoProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );

        jPanelPrincipal.add(jPanelInfoProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 390));

        jTextFieldEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEntradaActionPerformed(evt);
            }
        });
        jPanelPrincipal.add(jTextFieldEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 640, 740, 60));

        jTextAreaCategorias.setColumns(20);
        jTextAreaCategorias.setRows(5);
        jScrollPane1.setViewportView(jTextAreaCategorias);

        jPanelPrincipal.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 740, 250));

        getContentPane().add(jPanelPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldRelojActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldRelojActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldRelojActionPerformed

    private void jTextFieldEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEntradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEntradaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfazCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfazCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfazCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfazCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfazCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAceptarProducto;
    private javax.swing.JButton jButtonPujar;
    private javax.swing.JButton jButtonRechazarProducto;
    private javax.swing.JButton jButtonRetirarse;
    private javax.swing.JLabel jLabelTextoReloj;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanelElegirProducto;
    private javax.swing.JPanel jPanelInfoProducto;
    private javax.swing.JPanel jPanelPrincipal;
    private javax.swing.JPanel jPanelPujas;
    private javax.swing.JPanel jPanelReloj;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaCategorias;
    private javax.swing.JTextField jTextFieldEntrada;
    private javax.swing.JTextField jTextFieldReloj;
    // End of variables declaration//GEN-END:variables
}
